_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.15
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
C:
    value: 59
act_fn:
    value: ReLU
attention_dir:
    value: casual
attn_coeff:
    value: 0
batch_size:
    value: 3481
d_model:
    value: 128
diff_vocab:
    value: 0
epoch:
    value: 20000
eqn_sign:
    value: 0
frac:
    value: 0.8
func:
    value: __main__.<lambda>
funcs:
    value: 'lambda x: (x[0]+x[1])%59'
lr:
    value: 0.001
n_heads:
    value: 4
n_layers:
    value: 1
name:
    value: modadd_59
runid:
    value: A_repr_trans_1
save_embeddings:
    value: false
weight_decay:
    value: 2
